services:
  mysql:
    image: mysql:8.0
    container_name: mysql-stock
    environment:
      MYSQL_DATABASE: stock-microservice
      MYSQL_ROOT_PASSWORD: Thereis76_
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-net

  stock-service:
    build: .
    container_name: stock-service
    ports:
      - "9090:9090"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stock-microservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Thereis76_
    networks:
      - spring-net

volumes:
  mysql_data:

networks:
  spring-net: